import { hot, hot_rtp, drops_wins, new_svg, } from "@/utils"
import type { Game } from "@/utils/types";
export const arcadeGames:Game[] = [
     {
            "gameProviderId": 1029,
            "gameID": 49,
            "gameType": 6,
            "newGameType": 202,
            "rank": 12,
            "device": "d,m",
            "platform": "HTML5",
            "provider": "568winGames",
            "rtp": 0.985400,
            "rows": -1,
            "reels": -1,
            "lines": -1,
            "gameInfos": [
                {
                    "language": "en",
                    "gameName": "Plinko",
                    "gameIconUrl": "https://cdn-test.cdn568.net/568WinGames/49/plinko.jpg"
                },
                {
                    "language": "ZH_CN",
                    "gameName": "Plinko",
                    "gameIconUrl": "https://cdn-test.cdn568.net/568WinGames/49/plinko.jpg"
                }
            ],
            "supportedCurrencies": [
                "AED",
                "AUD",
                "BDT",
                "BRL",
                "CAD",
                "EUR",
                "GBP",
                "HKD",
                "IDO",
                "IDR",
                "INR",
                "JPY",
                "KHR",
                "KRW",
                "LAK",
                "MMK",
                "MYR",
                "NPR",
                "PHP",
                "SEK",
                "THB",
                "TMP",
                "USD",
                "VND",
                "VNO",
                "ZAR"
            ],
            "blockCountries": [
                "CN"
            ],
            "isMaintain": false,
            "isEnabled": true,
            "isProvideCommission": false,
            "hasHedgeBet": false,
            "providerStatus": "Online",
            "isProviderOnline": true
        },
];
export const topSlotGames:Game[] = [
                 {
                "gameProviderId": 1094,
                "gameID": 1,
                "gameType": 2,
                "newGameType": 201,
                "rank": 1,
                "device": "d/m",
                "platform": "HTML5",
                "provider": "AfricanBuffalo",
                "rtp": 0.950000,
                "rows": 3,
                "reels": 5,
                "lines": 25,
                "gameInfos": [
                    {
                        "language": "en",
                        "gameName": "African Buffalo(50)",
                        "gameIconUrl": "https://cdn-test.cdn568.net/AfricanBuffalo/1/1094_1_AfricanBuffalo.png"
                    },
                    {
                        "language": "MY_MM",
                        "gameName": "African Buffalo(50)",
                        "gameIconUrl": "https://cdn-test.cdn568.net/AfricanBuffalo/1/1094_1_AfricanBuffalo.png"
                    }
                ],
                "supportedCurrencies": [
                    "MMK",
                    "TMP"
                ],
                "blockCountries": [],
                "isMaintain": false,
                "isEnabled": true,
                "isProvideCommission": false,
                "hasHedgeBet": false,
                "providerStatus": "Online",
                "isProviderOnline": true
            },
                    {
                "gameProviderId": 3,
                "gameID": 438,
                "gameType": 2,
                "newGameType": 201,
                "rank": 1,
                "device": "d/m",
                "platform": "HTML5",
                "provider": "PragmaticPlay",
                "rtp": 0.965000,
                "rows": 5,
                "reels": 6,
                "lines": 20,
                "gameInfos": [
                    {
                        "language": "en",
                        "gameName": "Gates of Olympus 1000",
                        "gameIconUrl": "https://cdn-test.cdn568.net/PragmaticPlay/438/3_438_GatesofOlympus1000.png?v=6"
                    },
                    {
                        "language": "zh_cn",
                        "gameName": "奥林匹斯之门 1000™",
                        "gameIconUrl": "https://cdn-test.cdn568.net/images/games/PragmaticPlay/3_438_GatesofOlympus1000_CN.png"
                    }
                ],
                "supportedCurrencies": [
                    "KZT",
                    "IDO",
                    "IDR",
                    "TMP",
                    "VND",
                    "VNO",
                    "AUD",
                    "BDT",
                    "BND",
                    "BRL",
                    "CAD",
                    "CHF",
                    "CNY",
                    "EUR",
                    "GBP",
                    "HKD",
                    "INR",
                    "JPY",
                    "KHR",
                    "KRW",
                    "LAK",
                    "LKR",
                    "MMK",
                    "MXN",
                    "MYR",
                    "NGN",
                    "NOK",
                    "NPR",
                    "NZD",
                    "PHP",
                    "PKR",
                    "THB",
                    "TRY",
                    "USD",
                    "ZAR"
                ],
                "blockCountries": [],
                "isMaintain": false,
                "isEnabled": true,
                "isProvideCommission": false,
                "hasHedgeBet": false,
                "providerStatus": "Online",
                "isProviderOnline": true
            },
             {
            "gameProviderId": 1094,
            "gameID": 16,
            "gameType": 2,
            "newGameType": 201,
            "rank": 16,
            "device": "d/m",
            "platform": "HTML5",
            "provider": "AfricanBuffalo",
            "rtp": 0.950000,
            "rows": 0,
            "reels": 0,
            "lines": 0,
            "gameInfos": [
                {
                    "language": "en",
                    "gameName": "African Buffalo Megaways",
                    "gameIconUrl": "https://cdn-test.cdn568.net/AfricanBuffalo/16/1094_16_AfricanBuffaloMegaways.png"
                },
                {
                    "language": "zh_cn",
                    "gameName": "African Buffalo Megaways",
                    "gameIconUrl": "https://cdn-test.cdn568.net/AfricanBuffalo/16/1094_16_AfricanBuffaloMegaways.png"
                }
            ],
            "supportedCurrencies": [
                "MMK",
                "TMP"
            ],
            "blockCountries": [],
            "isMaintain": false,
            "isEnabled": true,
            "isProvideCommission": false,
            "hasHedgeBet": false,
            "providerStatus": "Online",
            "isProviderOnline": true
        },
        {
            "gameProviderId": 1094,
            "gameID": 15,
            "gameType": 2,
            "newGameType": 201,
            "rank": 15,
            "device": "d/m",
            "platform": "HTML5",
            "provider": "AfricanBuffalo",
            "rtp": 0.950000,
            "rows": 0,
            "reels": 0,
            "lines": 0,
            "gameInfos": [
                {
                    "language": "en",
                    "gameName": "Grand Dragons",
                    "gameIconUrl": "https://cdn-test.cdn568.net/AfricanBuffalo/15/1094_15_GrandDragons.png"
                },
                {
                    "language": "zh_cn",
                    "gameName": "Grand Dragons",
                    "gameIconUrl": "https://cdn-test.cdn568.net/AfricanBuffalo/15/1094_15_GrandDragons.png"
                }
            ],
            "supportedCurrencies": [
                "MMK",
                "TMP"
            ],
            "blockCountries": [],
            "isMaintain": false,
            "isEnabled": true,
            "isProvideCommission": false,
            "hasHedgeBet": false,
            "providerStatus": "Online",
            "isProviderOnline": true
        },
        {
            "gameProviderId": 1094,
            "gameID": 14,
            "gameType": 2,
            "newGameType": 201,
            "rank": 14,
            "device": "d/m",
            "platform": "HTML5",
            "provider": "AfricanBuffalo",
            "rtp": 0.950000,
            "rows": 0,
            "reels": 0,
            "lines": 0,
            "gameInfos": [
                {
                    "language": "en",
                    "gameName": "Happy Prosperous",
                    "gameIconUrl": "https://cdn-test.cdn568.net/AfricanBuffalo/14/1094_14_HappyProsperous.png"
                },
                {
                    "language": "zh_cn",
                    "gameName": "Happy Prosperous",
                    "gameIconUrl": "https://cdn-test.cdn568.net/AfricanBuffalo/14/1094_14_HappyProsperous.png"
                }
            ],
            "supportedCurrencies": [
                "MMK",
                "TMP"
            ],
            "blockCountries": [],
            "isMaintain": false,
            "isEnabled": true,
            "isProvideCommission": false,
            "hasHedgeBet": false,
            "providerStatus": "Online",
            "isProviderOnline": true
        },
        {
            "gameProviderId": 1094,
            "gameID": 13,
            "gameType": 2,
            "newGameType": 201,
            "rank": 13,
            "device": "d/m",
            "platform": "HTML5",
            "provider": "AfricanBuffalo",
            "rtp": 0.000000,
            "rows": 0,
            "reels": 0,
            "lines": 0,
            "gameInfos": [
                {
                    "language": "en",
                    "gameName": "Peace LongLife",
                    "gameIconUrl": "https://cdn-test.cdn568.net/AfricanBuffalo/13/1094_13_PeaceLongLife.png"
                },
                {
                    "language": "zh_cn",
                    "gameName": "Peace LongLife",
                    "gameIconUrl": "https://cdn-test.cdn568.net/AfricanBuffalo/13/1094_13_PeaceLongLife.png"
                }
            ],
            "supportedCurrencies": [
                "MMK",
                "TMP"
            ],
            "blockCountries": [],
            "isMaintain": false,
            "isEnabled": true,
            "isProvideCommission": false,
            "hasHedgeBet": false,
            "providerStatus": "Online",
            "isProviderOnline": true
        },
        {
            "gameProviderId": 1094,
            "gameID": 12,
            "gameType": 2,
            "newGameType": 201,
            "rank": 12,
            "device": "d/m",
            "platform": "HTML5",
            "provider": "AfricanBuffalo",
            "rtp": 0.950000,
            "rows": 0,
            "reels": 0,
            "lines": 0,
            "gameInfos": [
                {
                    "language": "en",
                    "gameName": "LuxuryLine Buffalo",
                    "gameIconUrl": "https://cdn-test.cdn568.net/AfricanBuffalo/12/1094_12_LuxuryLineBuffalo.png"
                },
                {
                    "language": "zh_cn",
                    "gameName": "LuxuryLine Buffalo",
                    "gameIconUrl": "https://cdn-test.cdn568.net/AfricanBuffalo/12/1094_12_LuxuryLineBuffalo.png"
                }
            ],
            "supportedCurrencies": [
                "MMK",
                "TMP"
            ],
            "blockCountries": [],
            "isMaintain": false,
            "isEnabled": true,
            "isProvideCommission": false,
            "hasHedgeBet": false,
            "providerStatus": "Online",
            "isProviderOnline": true
        },
        {
            "gameProviderId": 1094,
            "gameID": 11,
            "gameType": 2,
            "newGameType": 201,
            "rank": 11,
            "device": "d/m",
            "platform": "HTML5",
            "provider": "AfricanBuffalo",
            "rtp": 0.950000,
            "rows": 0,
            "reels": 0,
            "lines": 0,
            "gameInfos": [
                {
                    "language": "en",
                    "gameName": "Golden Century 88",
                    "gameIconUrl": "https://cdn-test.cdn568.net/AfricanBuffalo/11/1094_11_GoldenCentury88.png"
                },
                {
                    "language": "zh_cn",
                    "gameName": "Golden Century 88",
                    "gameIconUrl": "https://cdn-test.cdn568.net/AfricanBuffalo/11/1094_11_GoldenCentury88.png"
                }
            ],
            "supportedCurrencies": [
                "MMK",
                "TMP"
            ],
            "blockCountries": [],
            "isMaintain": false,
            "isEnabled": true,
            "isProvideCommission": false,
            "hasHedgeBet": false,
            "providerStatus": "Online",
            "isProviderOnline": true
        },
        {
            "gameProviderId": 1094,
            "gameID": 10,
            "gameType": 2,
            "newGameType": 201,
            "rank": 10,
            "device": "d/m",
            "platform": "HTML5",
            "provider": "AfricanBuffalo",
            "rtp": 0.950000,
            "rows": 0,
            "reels": 0,
            "lines": 0,
            "gameInfos": [
                {
                    "language": "en",
                    "gameName": "Autumn Moon 88",
                    "gameIconUrl": "https://cdn-test.cdn568.net/AfricanBuffalo/10/1094_10_AutumnMoon88.png"
                },
                {
                    "language": "zh_cn",
                    "gameName": "Autumn Moon 88",
                    "gameIconUrl": "https://cdn-test.cdn568.net/AfricanBuffalo/10/1094_10_AutumnMoon88.png"
                }
            ],
            "supportedCurrencies": [
                "MMK",
                "TMP"
            ],
            "blockCountries": [],
            "isMaintain": false,
            "isEnabled": true,
            "isProvideCommission": false,
            "hasHedgeBet": false,
            "providerStatus": "Online",
            "isProviderOnline": true
        },
        {
            "gameProviderId": 1094,
            "gameID": 9,
            "gameType": 2,
            "newGameType": 201,
            "rank": 9,
            "device": "d/m",
            "platform": "HTML5",
            "provider": "AfricanBuffalo",
            "rtp": 0.950000,
            "rows": 0,
            "reels": 0,
            "lines": 0,
            "gameInfos": [
                {
                    "language": "en",
                    "gameName": "Golden Century",
                    "gameIconUrl": "https://cdn-test.cdn568.net/AfricanBuffalo/9/1094_9_GoldenCentury.png"
                },
                {
                    "language": "zh_cn",
                    "gameName": "Golden Century",
                    "gameIconUrl": "https://cdn-test.cdn568.net/AfricanBuffalo/9/1094_9_GoldenCentury.png"
                }
            ],
            "supportedCurrencies": [
                "MMK",
                "TMP"
            ],
            "blockCountries": [],
            "isMaintain": false,
            "isEnabled": true,
            "isProvideCommission": false,
            "hasHedgeBet": false,
            "providerStatus": "Online",
            "isProviderOnline": true
        },
        {
            "gameProviderId": 1094,
            "gameID": 8,
            "gameType": 2,
            "newGameType": 201,
            "rank": 8,
            "device": "d/m",
            "platform": "HTML5",
            "provider": "AfricanBuffalo",
            "rtp": 0.950000,
            "rows": 0,
            "reels": 0,
            "lines": 0,
            "gameInfos": [
                {
                    "language": "en",
                    "gameName": "Autumn Moon",
                    "gameIconUrl": "https://cdn-test.cdn568.net/AfricanBuffalo/8/1094_8_AutumnMoon.png"
                },
                {
                    "language": "zh_cn",
                    "gameName": "Autumn Moon",
                    "gameIconUrl": "https://cdn-test.cdn568.net/AfricanBuffalo/8/1094_8_AutumnMoon.png"
                }
            ],
            "supportedCurrencies": [
                "MMK",
                "TMP"
            ],
            "blockCountries": [],
            "isMaintain": false,
            "isEnabled": true,
            "isProvideCommission": false,
            "hasHedgeBet": false,
            "providerStatus": "Online",
            "isProviderOnline": true
        },
        {
            "gameProviderId": 1094,
            "gameID": 7,
            "gameType": 2,
            "newGameType": 201,
            "rank": 7,
            "device": "d/m",
            "platform": "HTML5",
            "provider": "AfricanBuffalo",
            "rtp": 0.950000,
            "rows": 0,
            "reels": 0,
            "lines": 0,
            "gameInfos": [
                {
                    "language": "en",
                    "gameName": "Fortune Cat",
                    "gameIconUrl": "https://cdn-test.cdn568.net/AfricanBuffalo/7/1094_7_FortuneCat.png"
                },
                {
                    "language": "zh_cn",
                    "gameName": "Fortune Cat",
                    "gameIconUrl": "https://cdn-test.cdn568.net/AfricanBuffalo/7/1094_7_FortuneCat.png"
                }
            ],
            "supportedCurrencies": [
                "MMK",
                "TMP"
            ],
            "blockCountries": [],
            "isMaintain": false,
            "isEnabled": true,
            "isProvideCommission": false,
            "hasHedgeBet": false,
            "providerStatus": "Online",
            "isProviderOnline": true
        },
            {
                "gameProviderId": 3,
                "gameID": 567,
                "gameType": 2,
                "newGameType": 201,
                "rank": 2,
                "device": "d/m",
                "platform": "HTML5",
                "provider": "PragmaticPlay",
                "rtp": 0.970000,
                "rows": 4,
                "reels": 5,
                "lines": 1999,
                "gameInfos": [
                    {
                        "language": "en",
                        "gameName": "Mahjong Wins 2",
                        "gameIconUrl": "https://cdn-test.cdn568.net/PragmaticPlay/567/3_567_MahjongWins2.png?v=1"
                    },
                    {
                        "language": "zh_cn",
                        "gameName": "麻将大胜2",
                        "gameIconUrl": "https://cdn-test.cdn568.net/PragmaticPlay/567/3_567_MahjongWins2_CN.png"
                    }
                ],
                "supportedCurrencies": [
                    "KZT",
                    "IDO",
                    "IDR",
                    "TMP",
                    "VND",
                    "VNO",
                    "AUD",
                    "BDT",
                    "BND",
                    "BRL",
                    "CAD",
                    "CHF",
                    "CNY",
                    "EUR",
                    "GBP",
                    "HKD",
                    "INR",
                    "JPY",
                    "KHR",
                    "KRW",
                    "LAK",
                    "LKR",
                    "MMK",
                    "MXN",
                    "MYR",
                    "NGN",
                    "NOK",
                    "NPR",
                    "NZD",
                    "PHP",
                    "PKR",
                    "THB",
                    "TRY",
                    "USD",
                    "ZAR"
                ],
                "blockCountries": [],
                "isMaintain": false,
                "isEnabled": true,
                "isProvideCommission": false,
                "hasHedgeBet": false,
                "providerStatus": "Online",
                "isProviderOnline": true
            },
]
export const fishGames:Game[] = [

]
export const hotGames:Game[] = [

        {
            "badge":hot,
            "badge_1":drops_wins,
            "gameProviderId": 3,
            "gameID": 438,
            "gameType": 2,
            "newGameType": 201,
            "rank": 1,
            "device": "d/m",
            "platform": "HTML5",
            "provider": "PragmaticPlay",
            "rtp": 0.965000,
            "rows": 5,
            "reels": 6,
            "lines": 20,
            "gameInfos": [
                {
                    "language": "en",
                    "gameName": "Gates of Olympus 1000",
                    "gameIconUrl": "https://cdn-test.cdn568.net/PragmaticPlay/438/3_438_GatesofOlympus1000.png?v=6"
                },
                {
                    "language": "zh_cn",
                    "gameName": "奥林匹斯之门 1000™",
                    "gameIconUrl": "https://cdn-test.cdn568.net/images/games/PragmaticPlay/3_438_GatesofOlympus1000_CN.png"
                }
            ],

            "blockCountries": [],
            "isMaintain": false,
            "isEnabled": true,
            "isProvideCommission": false,
            "hasHedgeBet": false,
            "providerStatus": "Online",
            "isProviderOnline": true
        },
         {
            "gameProviderId": 1046,
            "gameID": 48,
            "gameType": 2,
            "newGameType": 201,
            "rank": 4,
            "device": "d/m",
            "platform": "HTML5",
            "provider": "FaChai",
            "rtp": 0.965000,
            "rows": -1,
            "reels": -1,
            "lines": 0,
            "gameInfos": [
                {
                    "language": "en",
                    "gameName": "QUEEN OF INCA",
                    "gameIconUrl": "https://cdn-test.cdn568.net/FaChai/48/1046_48_QUEENOFINCA.jpg"
                },
                {
                    "language": "zh_cn",
                    "gameName": "印加女皇",
                    "gameIconUrl": "https://cdn-test.cdn568.net/FaChai/48/1046_48_QUEENOFINCA_CN.jpg"
                }
            ],
            "supportedCurrencies": [
                "TMP",
                "AED",
                "AUD",
                "BDT",
                "BND",
                "BRL",
                "CAD",
                "CHF",
                "CLP",
                "CNY",
                "EUR",
                "GBP",
                "HKD",
                "IDR",
                "IDO",
                "INR",
                "JPY",
                "KRW",
                "LAK",
                "LKR",
                "MXN",
                "MYR",
                "NGN",
                "NOK",
                "NPR",
                "NZD",
                "PHP",
                "PKR",
                "RUB",
                "SEK",
                "SGD",
                "THB",
                "TRY",
                "USD",
                "VND",
                "VNO",
                "ZAR",
                "MMK"
            ],
            "blockCountries": [],
            "isMaintain": false,
            "isEnabled": true,
            "isProvideCommission": false,
            "hasHedgeBet": false,
            "providerStatus": "Online",
            "isProviderOnline": true,
               "badge":hot,
               "badge_1":hot_rtp
          
        },

      
        
        {
              "badge":hot,
              "badge_1":hot_rtp,
            "gameProviderId": 3,
            "gameID": 448,
            "gameType": 2,
            "newGameType": 201,
            "rank": 11,
            "device": "d/m",
            "platform": "HTML5",
            "provider": "PragmaticPlay",
            "rtp": 0.964800,
            "rows": 4,
            "reels": 5,
            "lines": 1024,
            "gameInfos": [
                {
                    "language": "en",
                    "gameName": "Mahjong Wins Bonus",
                    "gameIconUrl": "https://cdn-test.cdn568.net/PragmaticPlay/448/3_448_MahjongWinsBonus.png?v=1"
                },
                {
                    "language": "zh_cn",
                    "gameName": "麻将大胜Bonus",
                    "gameIconUrl": "https://cdn-test.cdn568.net/images/games/PragmaticPlay/3_448_MahjongWinsBonus_CN.png"
                }
            ],
            "supportedCurrencies": [
                "KZT",
                "IDO",
                "IDR",
                "TMP",
                "VND",
                "VNO",
                "AUD",
                "BDT",
                "BND",
                "BRL",
                "CAD",
                "CHF",
                "CNY",
                "EUR",
                "GBP",
                "HKD",
                "INR",
                "JPY",
                "KHR",
                "KRW",
                "LAK",
                "LKR",
                "MMK",
                "MXN",
                "MYR",
                "NGN",
                "NOK",
                "NPR",
                "NZD",
                "PHP",
                "PKR",
                "THB",
                "TRY",
                "USD",
                "ZAR"
            ],
            "blockCountries": [],
            "isMaintain": false,
            "isEnabled": true,
            "isProvideCommission": false,
            "hasHedgeBet": false,
            "providerStatus": "Online",
            "isProviderOnline": true
        },
         {
         "badge":hot,
            "badge_1":hot_rtp,
            "gameProviderId": 3,
            "gameID": 473,
            "gameType": 2,
            "newGameType": 201,
            "rank": 5,
            "device": "d/m",
            "platform": "HTML5",
            "provider": "PragmaticPlay",
            "rtp": 0.965300,
            "rows": 7,
            "reels": 7,
            "lines": 20,
            "gameInfos": [
                {
                    "language": "en",
                    "gameName": "Sugar Rush 1000",
                    "gameIconUrl": "https://cdn-test.cdn568.net/PragmaticPlay/473/3_473_SugarRush1000.png?v=6"
                },
                {
                    "language": "zh_cn",
                    "gameName": "极速糖果1000",
                    "gameIconUrl": "https://cdn-test.cdn568.net/images/games/PragmaticPlay/3_473_SugarRush1000_CN.png"
                }
            ],
            "supportedCurrencies": [
                "KZT",
                "IDO",
                "IDR",
                "TMP",
                "VND",
                "VNO",
                "AUD",
                "BDT",
                "BND",
                "BRL",
                "CAD",
                "CHF",
                "CNY",
                "EUR",
                "GBP",
                "HKD",
                "INR",
                "JPY",
                "KHR",
                "KRW",
                "LAK",
                "LKR",
                "MMK",
                "MXN",
                "MYR",
                "NGN",
                "NOK",
                "NPR",
                "NZD",
                "PHP",
                "PKR",
                "THB",
                "TRY",
                "USD",
                "ZAR"
            ],
            "blockCountries": [],
            "isMaintain": false,
            "isEnabled": true,
            "isProvideCommission": false,
            "hasHedgeBet": false,
            "providerStatus": "Online",
            "isProviderOnline": true
        },
        {
            "gameProviderId": 1034,
            "gameID": 75,
            "gameType": 2,
            "newGameType": 201,
            "rank": 1,
            "device": "d/m",
            "platform": "HTML5",
            "provider": "AdvantPlay",
            "rtp": 0.960000,
            "rows": 0,
            "reels": 0,
            "lines": 720,
            "gameInfos": [
                {
                    "language": "en",
                    "gameName": "Mahjong Roar",
                    "gameIconUrl": "https://cdn-test.cdn568.net/AdvantPlay/75/1034_75_MahjongRoar.jpg"
                },
                {
                    "language": "zh_cn",
                    "gameName": "龙腾麻将",
                    "gameIconUrl": "https://cdn-test.cdn568.net/AdvantPlay/75/1034_75_MahjongRoar_CN.jpg"
                }
            ],
            "supportedCurrencies": [
                
                "RUB",
                "SEK",
                "THB",
                "USD",
                "UCC",
                "VNO",
                "VND",
                "ZAR"
            ],
            "blockCountries": [],
            "isMaintain": false,
            "isEnabled": true,
            "isProvideCommission": false,
            "hasHedgeBet": false,
            "providerStatus": "Online",
            "isProviderOnline": true,
              "badge":drops_wins,
                 "badge_1":hot_rtp
           
        },  {
            "badge":drops_wins,
            "gameProviderId": 1034,
            "gameID": 76,
            "gameType": 2,
            "newGameType": 201,
            "rank": 3,
            "device": "d/m",
            "platform": "HTML5",
            "provider": "AdvantPlay",
            "rtp": 0.970500,
            "rows": 0,
            "reels": 0,
            "lines": 0,
            "gameInfos": [
                {
                    "language": "en",
                    "gameName": "Golden Egypt",
                    "gameIconUrl": "https://cdn-test.cdn568.net/AdvantPlay/76/1034_76_GoldenEgypt.jpg"
                },
                {
                    "language": "zh_cn",
                    "gameName": "埃及辉光",
                    "gameIconUrl": "https://cdn-test.cdn568.net/AdvantPlay/76/1034_76_GoldenEgypt_CN.jpg"
                }
            ],
            "supportedCurrencies": [
                "AED",
                "AUD",
                "BDT",
                "BND",
                "KHR",
                "BRL",
                "CAD",
                "CHF",
                "CNY",
                "EUR",
                "GBP",
                "HKD",
                "IDO",
                "TMP",
                "IDR",
                "INR",
                "JPY",
                "KRW",
                "LAK",
                "MMK",
                "MXN",
                "MYR",
                "NOK",
                "NPR",
                "NZD",
                "RUB",
                "SEK",
                "THB",
                "USD",
                "UCC",
                "VNO",
                "VND",
                "ZAR"
            ],
            "blockCountries": [],
            "isMaintain": false,
            "isEnabled": true,
            "isProvideCommission": false,
            "hasHedgeBet": false,
            "providerStatus": "Online",
            "isProviderOnline": true
        },
         

        {
            "gameProviderId": 3,
            "gameID": 388,
            "gameType": 2,
            "newGameType": 201,
            "rank": 3,
            "device": "d/m",
            "platform": "HTML5",
            "provider": "PragmaticPlay",
            "rtp": 0.965000,
            "rows": 5,
            "reels": 6,
            "lines": 20,
            "gameInfos": [
                {
                    "language": "en",
                    "gameName": "Starlight Princess 1000",
                    "gameIconUrl": "https://cdn-test.cdn568.net/PragmaticPlay/388/3_388_StarlightPrincess1000.png?v=7"
                },
                {
                    "language": "zh_cn",
                    "gameName": "星光公主™ 1000",
                    "gameIconUrl": "https://cdn-test.cdn568.net/images/games/PragmaticPlay/3_388_StarlightPrincess1000_CN.png?v=1"
                }
            ],
            "supportedCurrencies": [
                "KZT",
                "IDO",
                "IDR",
                "TMP",
                "VND",
                "VNO",
                "AUD",
                "BDT",
                "BND",
                "BRL",
                "CAD",
                "CHF",
                "CNY",
                "EUR",
                "GBP",
                "HKD",
                "INR",
                "JPY",
                "KHR",
                "KRW",
                "LAK",
                "LKR",
                "MMK",
                "MXN",
                "MYR",
                "NGN",
                "NOK",
                "NPR",
                "NZD",
                "PHP",
                "PKR",
                "THB",
                "TRY",
                "USD",
                "ZAR"
            ],
            "blockCountries": [],
            "isMaintain": false,
            "isEnabled": true,
            "isProvideCommission": false,
            "hasHedgeBet": false,
            "providerStatus": "Online",
            "isProviderOnline": true,
                "badge":drops_wins,
         
        },
                 {
            "gameProviderId": 1046,
            "gameID": 51,
            "gameType": 2,
            "newGameType": 201,
            "rank": 2,
            "device": "d/m",
            "platform": "HTML5",
            "provider": "FaChai",
            "rtp": 0.965000,
            "rows": 5,
            "reels": 6,
            "lines": 0,
            "gameInfos": [
                {
                    "language": "en",
                    "gameName": "POKER WIN",
                    "gameIconUrl": "https://cdn-test.cdn568.net/FaChai/51/1046_51_POKERWIN.jpg"
                },
                {
                    "language": "zh_cn",
                    "gameName": "至尊王牌",
                    "gameIconUrl": "https://cdn-test.cdn568.net/FaChai/51/1046_51_POKERWIN_CN.jpg"
                }
            ],
            "supportedCurrencies": [
                "TMP",
                "AED",
                "AUD",
                "BDT",
                "BND",
                "BRL",
                "CAD",
                "CHF",
                "CLP",
                "CNY",
                "EUR",
                "GBP",
                "HKD",
                "IDR",
                "IDO",
                "INR",
                "JPY",
                "KRW",
                "LAK",
                "LKR",
                "MXN",
                "MYR",
                "NGN",
                "NOK",
                "NPR",
                "NZD",
                "PHP",
                "PKR",
                "RUB",
                "SEK",
                "SGD",
                "THB",
                "TRY",
                "USD",
                "VND",
                "VNO",
                "ZAR",
                "MMK"
            ],
            "blockCountries": [],
            "isMaintain": false,
            "isEnabled": true,
            "isProvideCommission": false,
            "hasHedgeBet": false,
            "providerStatus": "Online",
            "isProviderOnline": true,
            "badge":drops_wins
        },
                 
         {
            "gameProviderId": 1094,
            "gameID": 2,
            "gameType": 2,
            "newGameType": 201,
            "rank": 3,
            "device": "d/m",
            "platform": "HTML5",
            "provider": "AfricanBuffalo",
            "rtp": 0.950000,
            "rows": 3,
            "reels": 5,
            "lines": 25,
            "gameInfos": [
                {
                    "language": "en",
                    "gameName": "African Buffalo(500)",
                    "gameIconUrl": "https://cdn-test.cdn568.net/AfricanBuffalo/1/1094_1_AfricanBuffalo.png"
                },
                {
                    "language": "MY_MM",
                    "gameName": "African Buffalo(500)",
                    "gameIconUrl": "https://cdn-test.cdn568.net/AfricanBuffalo/1/1094_1_AfricanBuffalo.png"
                }
            ],
            "supportedCurrencies": [
                "MMK",
                "TMP"
            ],
            "blockCountries": [],
            "isMaintain": false,
            "isEnabled": true,
            "isProvideCommission": false,
            "hasHedgeBet": false,
            "providerStatus": "Online",
            "isProviderOnline": true,
                "badge":hot
        },
       {
            "gameProviderId": 1034,
            "gameID": 46,
            "gameType": 2,
            "newGameType": 201,
            "rank": 2,
            "device": "d/m",
            "platform": "HTML5",
            "provider": "AdvantPlay",
            "rtp": 0.970800,
            "rows": 3,
            "reels": 5,
            "lines": 25,
            "gameInfos": [
                {
                    "language": "en",
                    "gameName": "Dragon Chi’s Quest",
                    "gameIconUrl": "https://cdn-test.cdn568.net/AdvantPlay/46/1034_46_DragonChisQuest.jpg"
                },
                {
                    "language": "zh_cn",
                    "gameName": "祥龙极气",
                    "gameIconUrl": "https://cdn-test.cdn568.net/AdvantPlay/46/1034_46_DragonChisQuest_CN.jpg"
                }
            ],
            "supportedCurrencies": [
                "AED",
                "AUD",
                "BDT",
                "BND",
                "KHR",
                "BRL",
                "CAD",
                "CHF",
                "CNY",
                "EUR",
                "GBP",
                "HKD",
                "IDO",
                "TMP",
                "IDR",
                "INR",
                "JPY",
                "KRW",
                "LAK",
                "MMK",
                "MXN",
                "MYR",
                "NOK",
                "NPR",
                "NZD",
                "RUB",
                "SEK",
                "THB",
                "USD",
                "UCC",
                "VNO",
                "VND",
                "ZAR"
            ],
            "blockCountries": [],
            "isMaintain": false,
            "isEnabled": true,
            "isProvideCommission": false,
            "hasHedgeBet": false,
            "providerStatus": "Online",
            "isProviderOnline": true,
            "badge":hot,
            "badge_1":hot_rtp
        },
         {
            "gameProviderId": 3,
            "gameID": 596,
            "gameType": 2,
            "newGameType": 201,
            "rank": 6,
            "device": "d/m",
            "platform": "HTML5",
            "provider": "PragmaticPlay",
            "rtp": 0.965000,
            "rows": 5,
            "reels": 6,
            "lines": 20,
            "gameInfos": [
                {
                    "language": "en",
                    "gameName": "Gates of Olympus Super Scatter",
                    "gameIconUrl": "https://cdn-test.cdn568.net/PragmaticPlay/596/3_596_GatesofOlympusSuperScatter.png"
                }
                , {
                    "language": "en",
                    "gameName": "Gates of Olympus Super Scatter",
                    "gameIconUrl": "https://cdn-test.cdn568.net/PragmaticPlay/596/3_596_GatesofOlympusSuperScatter.png"
                }
            ],
            "supportedCurrencies": [
                "KZT",
                "IDO",
                "IDR",
                "TMP",
                "VND",
                "VNO",
                "AUD",
                "BDT",
                "BND",
                "BRL",
                "CAD",
                "CHF",
                "CNY",
                "EUR",
                "GBP",
                "HKD",
                "INR",
                "JPY",
                "KHR",
                "KRW",
                "LAK",
                "LKR",
                "MMK",
                "MXN",
                "MYR",
                "NGN",
                "NOK",
                "NPR",
                "NZD",
                "PHP",
                "PKR",
                "THB",
                "TRY",
                "USD",
                "ZAR"
            ],
            "blockCountries": [],
            "isMaintain": false,
            "isEnabled": true,
            "isProvideCommission": false,
            "hasHedgeBet": false,
            "providerStatus": "Online",
            "isProviderOnline": true,
            "badge":hot
        },
          {
            "gameProviderId": 1034,
            "gameID": 74,
            "gameType": 2,
            "newGameType": 201,
            "rank": 4,
            "device": "d/m",
            "platform": "HTML5",
            "provider": "AdvantPlay",
            "rtp": 0.974800,
            "rows": 5,
            "reels": 6,
            "lines": 32400,
            "gameInfos": [
                {
                    "language": "en",
                    "gameName": "LABUBU: Fall In Wild",
                    "gameIconUrl": "https://cdn-test.cdn568.net/AdvantPlay/74/1034_74_LABUBUFallInWild.jpg"
                },
                {
                    "language": "zh_cn",
                    "gameName": "LABUBU: 春天野在家",
                    "gameIconUrl": "https://cdn-test.cdn568.net/AdvantPlay/74/1034_74_LABUBUFallInWild_CN.jpg"
                }
            ],
            "supportedCurrencies": [
                "AED",
                "AUD",
                "BDT",
                "BND",
                "KHR",
                "BRL",
                "CAD",
                "CHF",
                "CNY",
                "EUR",
                "GBP",
                "HKD",
                "IDO",
                "TMP",
                "IDR",
                "INR",
                "JPY",
                "KRW",
                "LAK",
                "MMK",
                "MXN",
                "MYR",
                "NOK",
                "NPR",
                "NZD",
                "RUB",
                "SEK",
                "THB",
                "USD",
                "UCC",
                "VNO",
                "VND",
                "ZAR"
            ],
            "blockCountries": [],
            "isMaintain": false,
            "isEnabled": true,
            "isProvideCommission": false,
            "hasHedgeBet": false,
            "providerStatus": "Online",
            "isProviderOnline": true,
            "badge":hot
        },

]
export const topGames :Game[]= [
]
export const RTPGames:Game[] = [
     {
            "gameProviderId": 1046,
            "gameID": 52,
            "gameType": 2,
            "newGameType": 201,
            "rank": 1,
            "device": "d/m",
            "platform": "HTML5",
            "provider": "FaChai",
            "rtp": 0.965000,
            "rows": 0,
            "reels": 0,
            "lines": 0,
            "gameInfos": [
                {
                    "language": "en",
                    "gameName": "CHINESE NEW YEAR MOREWAYS",
                    "gameIconUrl": "https://cdn-test.cdn568.net/FaChai/52/1046_52_CHINESENEWYEARMOREWAYS.jpg"
                },
                {
                    "language": "zh_cn",
                    "gameName": "大过年路路发",
                    "gameIconUrl": "https://cdn-test.cdn568.net/FaChai/52/1046_52_CHINESENEWYEARMOREWAYS_CN.jpg"
                }
            ],
            "supportedCurrencies": [
                "TMP",
                "AED",
                "AUD",
                "BDT",
                "BND",
                "BRL",
                "CAD",
                "CHF",
                "CLP",
                "CNY",
                "EUR",
                "GBP",
                "HKD",
                "IDR",
                "IDO",
                "INR",
                "JPY",
                "KRW",
                "LAK",
                "LKR",
                "MXN",
                "MYR",
                "NGN",
                "NOK",
                "NPR",
                "NZD",
                "PHP",
                "PKR",
                "RUB",
                "SEK",
                "SGD",
                "THB",
                "TRY",
                "USD",
                "VND",
                "VNO",
                "ZAR",
                "MMK"
            ],
            "blockCountries": [],
            "isMaintain": false,
            "isEnabled": true,
            "isProvideCommission": false,
            "hasHedgeBet": false,
            "providerStatus": "Online",
            "isProviderOnline": true,
            "badge":drops_wins,
            "badge_1":hot_rtp
        },
     {
            "gameProviderId": 1046,
            "gameID": 5,
            "gameType": 2,
            "newGameType": 201,
            "rank": 5,
            "device": "d,m",
            "platform": "HTML5",
            "provider": "FaChai",
            "rtp": 0.965000,
            "rows": 3,
            "reels": 5,
            "lines": 243,
            "gameInfos": [
                {
                    "language": "en",
                    "gameName": "LUCKY FORTUNES",
                    "gameIconUrl": "https://cdn-test.cdn568.net/Fachai/5/1046_5_LUCKYFORTUNES.jpg"
                },
                {
                    "language": "ZH_CN",
                    "gameName": "财富连连",
                    "gameIconUrl": "https://cdn-test.cdn568.net/Fachai/5/1046_5_LUCKYFORTUNES_CN.jpg"
                }
            ],
            "supportedCurrencies": [
                "TMP",
                "AED",
                "AUD",
                "BDT",
                "BND",
                "BRL",
                "CAD",
                "CHF",
                "CLP",
                "CNY",
                "EUR",
                "GBP",
                "HKD",
                "IDR",
                "IDO",
                "INR",
                "JPY",
                "KRW",
                "LAK",
                "LKR",
                "MXN",
                "MYR",
                "NGN",
                "NOK",
                "NPR",
                "NZD",
                "PHP",
                "PKR",
                "RUB",
                "SEK",
                "SGD",
                "THB",
                "TRY",
                "USD",
                "VND",
                "VNO",
                "ZAR",
                "MMK"
            ],
            "blockCountries": [],
            "isMaintain": false,
            "isEnabled": true,
            "isProvideCommission": true,
            "hasHedgeBet": false,
            "providerStatus": "Online",
            "isProviderOnline": true,
               "badge":drops_wins,
             "badge_1":hot_rtp
        },
         {
            "gameProviderId": 3,
            "gameID": 494,
            "gameType": 2,
            "newGameType": 201,
            "rank": 7,
            "device": "d/m",
            "platform": "HTML5",
            "provider": "PragmaticPlay",
            "rtp": 0.965300,
            "rows": 5,
            "reels": 6,
            "lines": 20,
            "gameInfos": [
                {
                    "language": "en",
                    "gameName": "Sweet Bonanza 1000",
                    "gameIconUrl": "https://cdn-test.cdn568.net/PragmaticPlay/494/3_494_SweetBonanza1000.png?v=6"
                },
                {
                    "language": "zh_cn",
                    "gameName": "甜入心扉 1000",
                    "gameIconUrl": "https://cdn-test.cdn568.net/images/games/PragmaticPlay/3_494_SweetBonanza1000_CN.png"
                }
            ],
            "supportedCurrencies": [
                "KZT",
                "IDO",
                "IDR",
                "TMP",
                "VND",
                "VNO",
                "AUD",
                "BDT",
                "BND",
                "BRL",
                "CAD",
                "CHF",
                "CNY",
                "EUR",
                "GBP",
                "HKD",
                "INR",
                "JPY",
                "KHR",
                "KRW",
                "LAK",
                "LKR",
                "MMK",
                "MXN",
                "MYR",
                "NGN",
                "NOK",
                "NPR",
                "NZD",
                "PHP",
                "PKR",
                "THB",
                "TRY",
                "USD",
                "ZAR"
            ],
            "blockCountries": [],
            "isMaintain": false,
            "isEnabled": true,
            "isProvideCommission": false,
            "hasHedgeBet": false,
            "providerStatus": "Online",
            "isProviderOnline": true,
              "badge":drops_wins,
             "badge_1":hot_rtp
        },
        
         {
            "gameProviderId": 35,
            "gameID": 65,
            "gameType": 2,
            "newGameType": 201,
            "rank": 1,
            "device": "d/m",
            "platform": "HTML5",
            "provider": "PGSoft",
            "rtp": 0.969200,
            "rows": 0,
            "reels": 0,
            "lines": 20,
            "gameInfos": [
                {
                    "language": "en",
                    "gameName": "Mahjong Ways",
                    "gameIconUrl": "https://cdn-test.cdn568.net/images/games/PGSoft/35_65_MahjongWays.jpg"
                },
                {
                    "language": "zh_cn",
                    "gameName": "麻将胡了",
                    "gameIconUrl": "https://cdn-test.cdn568.net/images/games/PGSoft/35_65_MahjongWays_CN.jpg"
                },
                {
                    "language": "zh_tw",
                    "gameName": "麻将胡了",
                    "gameIconUrl": "https://cdn-test.cdn568.net/images/games/PGSoft/35_65_MahjongWays_CN.jpg"
                }
            ],
            "supportedCurrencies": [
                "TMP",
                "BDT",
                "BRL",
                "CNY",
                "EUR",
                "IDR",
                "INR",
                "JPY",
                "KHR",
                "KRW",
                "LAK",
                "MMK",
                "MXN",
                "PHP",
                "THB",
                "USD",
                "VND"
            ],
            "blockCountries": [],
            "isMaintain": false,
            "isEnabled": true,
            "isProvideCommission": false,
            "hasHedgeBet": false,
            "providerStatus": "Online",
            "isProviderOnline": true,
               "badge":drops_wins,
            "badge_1":hot_rtp
        },
        {
            "gameProviderId": 35,
            "gameID": 74,
            "gameType": 2,
            "newGameType": 201,
            "rank": 2,
            "device": "d/m",
            "platform": "HTML5",
            "provider": "PGSoft",
            "rtp": 0.969500,
            "rows": 0,
            "reels": 0,
            "lines": 20,
            "gameInfos": [
                {
                    "language": "en",
                    "gameName": "Mahjong Ways 2",
                    "gameIconUrl": "https://cdn-test.cdn568.net/images/games/PGSoft/35_74_MahjongWays2.png"
                },
                {
                    "language": "zh_cn",
                    "gameName": "麻将胡了2",
                    "gameIconUrl": "https://cdn-test.cdn568.net/images/games/PGSoft/35_74_MahjongWays2_CN.png"
                },
                {
                    "language": "zh_tw",
                    "gameName": "麻將胡了2",
                    "gameIconUrl": "https://cdn-test.cdn568.net/images/games/PGSoft/35_74_MahjongWays2_CN.png"
                }
            ],
            "supportedCurrencies": [
                "TMP",
                "BDT",
                "BRL",
                "CNY",
                "EUR",
                "IDR",
                "INR",
                "JPY",
                "KHR",
                "KRW",
                "LAK",
                "MMK",
                "MXN",
                "PHP",
                "THB",
                "USD",
                "VND"
            ],
            "blockCountries": [],
            "isMaintain": false,
            "isEnabled": true,
            "isProvideCommission": false,
            "hasHedgeBet": false,
            "providerStatus": "Online",
            "isProviderOnline": true,
               "badge":drops_wins,
            "badge_1":hot_rtp
        },
         {
            "gameProviderId": 3,
            "gameID": 287,
            "gameType": 2,
            "newGameType": 201,
            "rank": 12,
            "device": "d/m",
            "platform": "HTML5",
            "provider": "PragmaticPlay",
            "rtp": 0.970000,
            "rows": 7,
            "reels": 7,
            "lines": 20,
            "gameInfos": [
                {
                    "language": "en",
                    "gameName": "Sugar Rush",
                    "gameIconUrl": "https://cdn-test.cdn568.net/PragmaticPlay/287/3_287_SugarRush.png?v=1"
                },
                {
                    "language": "zh_cn",
                    "gameName": "极速糖果",
                    "gameIconUrl": "https://cdn-test.cdn568.net/PragmaticPlay/287/3_287_SugarRush_CN.png"
                }
            ],
            "supportedCurrencies": [
                "KZT",
                "IDO",
                "IDR",
                "TMP",
                "VND",
                "VNO",
                "AUD",
                "BDT",
                "BND",
                "BRL",
                "CAD",
                "CHF",
                "CNY",
                "EUR",
                "GBP",
                "HKD",
                "INR",
                "JPY",
                "KHR",
                "KRW",
                "LAK",
                "LKR",
                "MMK",
                "MXN",
                "MYR",
                "NGN",
                "NOK",
                "NPR",
                "NZD",
                "PHP",
                "PKR",
                "THB",
                "TRY",
                "USD",
                "ZAR"
            ],
            "blockCountries": [],
            "isMaintain": false,
            "isEnabled": true,
            "isProvideCommission": false,
            "hasHedgeBet": false,
            "providerStatus": "Online",
            "isProviderOnline": true,
            "badge":hot_rtp,
            "badge_1":drops_wins
        },
         {
            "gameProviderId": 1079,
            "gameID": 49,
            "gameType": 2,
            "newGameType": 201,
            "rank": 3,
            "device": "d/m",
            "platform": "HTML5",
            "provider": "Fastspin",
            "rtp": 0.966100,
            "rows": 4,
            "reels": 5,
            "lines": 2000,
            "gameInfos": [
                {
                    "language": "en",
                    "gameName": "Mahjong Princess",
                    "gameIconUrl": "https://cdn-test.cdn568.net/Fastspin/49/1079_49_MahjongPrincess.png"
                },
                {
                    "language": "zh_cn",
                    "gameName": "麻将女神",
                    "gameIconUrl": "https://cdn-test.cdn568.net/Fastspin/49/1079_49_MahjongPrincess_CN.png"
                }
            ],
            "supportedCurrencies": [
                "RUB",
                "SAR",
                "SEK",
                "THB",
                "TJS",
                "TMT",
                "TND",
                "TRY",
                "TZS",
                "UAH",
                "UGX",
                "USD",
                "VND",
                "VNO",
                "XAF",
                "XOF",
                "ZAR",
                "ZMW",
                "TMP",
                "AED",
                "AMD",
                "ARS",
                "AUD",
                "AZN",
                "BAM",
                "BDT",
                "BGN",
                "BIF",
                "BND",
                "BRL",
                "BYN",
                "CAD",
                "CHF",
                "CLP",
                "CNY",
                "COP",
                "CRC",
                "CZK",
                "DKK",
                "DZD",
                "EGP",
                "BOP",
                "DOP",
                "ETB",
                "EUR",
                "GBP",
                "GEL",
                "GHS",
                "GTQ",
                "HKD",
                "HUF",
                "IDO",
                "IDR",
                "ILS",
                "INR",
                "IRR",
                "JPY",
                "KES",
                "KGS",
                "KHR",
                "KRW",
                "KZT",
                "LAK",
                "LBP",
                "LKR",
                "MAD",
                "MDL",
                "MMK",
                "MNT",
                "MXN",
                "MYK",
                "MYR",
                "MZN",
                "NGN",
                "NOK",
                "NPR",
                "NZD",
                "PEN",
                "PHP",
                "PKR",
                "PLN",
                "PYG",
                "QAR",
                "RON",
                "RSD"
            ],
            "blockCountries": [],
            "isMaintain": false,
            "isEnabled": true,
            "isProvideCommission": false,
            "hasHedgeBet": false,
            "providerStatus": "Online",
            "isProviderOnline": true,
            "badge":drops_wins
        },
        {
            "gameProviderId": 1079,
            "gameID": 5,
            "gameType": 2,
            "newGameType": 201,
            "rank": 2,
            "device": "d,m",
            "platform": "HTML5",
            "provider": "Fastspin",
            "rtp": 0.967000,
            "rows": 4,
            "reels": 5,
            "lines": 1024,
            "gameInfos": [
                {
                    "language": "en",
                    "gameName": "Adventure To The West",
                    "gameIconUrl": "https://cdn-test.cdn568.net/Fastspin/5/1079_5_AdventureToTheWest.png"
                },
                {
                    "language": "ZH_CN",
                    "gameName": "嘻游记",
                    "gameIconUrl": "https://cdn-test.cdn568.net/Fastspin/5/1079_5_AdventureToTheWest_CN.png"
                }
            ],
            "supportedCurrencies": [
                "RUB",
                "SAR",
                "SEK",
                "THB",
                "TJS",
                "TMT",
                "TND",
                "TRY",
                "TZS",
                "UAH",
                "UGX",
                "USD",
                "VND",
                "VNO",
                "XAF",
                "XOF",
                "ZAR",
                "ZMW",
                "TMP",
                "AED",
                "AMD",
                "ARS",
                "AUD",
                "AZN",
                "BAM",
                "BDT",
                "BGN",
                "BIF",
                "BND",
                "BRL",
                "BYN",
                "CAD",
                "CHF",
                "CLP",
                "CNY",
                "COP",
                "CRC",
                "CZK",
                "DKK",
                "DZD",
                "EGP",
                "BOP",
                "DOP",
                "ETB",
                "EUR",
                "GBP",
                "GEL",
                "GHS",
                "GTQ",
                "HKD",
                "HUF",
                "IDO",
                "IDR",
                "ILS",
                "INR",
                "IRR",
                "JPY",
                "KES",
                "KGS",
                "KHR",
                "KRW",
                "KZT",
                "LAK",
                "LBP",
                "LKR",
                "MAD",
                "MDL",
                "MMK",
                "MNT",
                "MXN",
                "MYK",
                "MYR",
                "MZN",
                "NGN",
                "NOK",
                "NPR",
                "NZD",
                "PEN",
                "PHP",
                "PKR",
                "PLN",
                "PYG",
                "QAR",
                "RON",
                "RSD"
            ],
            "blockCountries": [],
            "isMaintain": false,
            "isEnabled": true,
            "isProvideCommission": false,
            "hasHedgeBet": false,
            "providerStatus": "Online",
            "isProviderOnline": true,
            "badge":drops_wins
        },
        {
            "gameProviderId": 1079,
            "gameID": 16,
            "gameType": 2,
            "newGameType": 201,
            "rank": 1,
            "device": "d,m",
            "platform": "HTML5",
            "provider": "Fastspin",
            "rtp": 0.966000,
            "rows": 8,
            "reels": 6,
            "lines": 200704,
            "gameInfos": [
                {
                    "language": "en",
                    "gameName": "The Great Safari",
                    "gameIconUrl": "https://cdn-test.cdn568.net/Fastspin/16/1079_16_TheGreatSafari.png"
                },
                {
                    "language": "ZH_CN",
                    "gameName": "草原王者",
                    "gameIconUrl": "https://cdn-test.cdn568.net/Fastspin/16/1079_16_TheGreatSafari_CN.png"
                }
            ],
 
            "blockCountries": [],
            "isMaintain": false,
            "isEnabled": true,
            "isProvideCommission": false,
            "hasHedgeBet": false,
            "providerStatus": "Online",
            "isProviderOnline": true,
               "badge":drops_wins,
           
        },
         {
            "gameProviderId": 1020,
            "gameID": 116,
            "gameType": 2,
            "newGameType": 201,
            "rank": 1,
            "device": "d/m",
            "platform": "HTML5",
            "provider": "JiLiGaming",
            "rtp": 0.000000,
            "rows": 0,
            "reels": 0,
            "lines": 0,
            "gameInfos": [
                {
                    "language": "en",
                    "gameName": "Fortune Gems 2",
                    "gameIconUrl": "https://cdn-test.cdn568.net/JiLiGaming/116/1020_116_FortuneGems2.png"
                },
                {
                    "language": "zh_cn",
                    "gameName": "迦羅寶石2",
                    "gameIconUrl": "https://cdn-test.cdn568.net/JiLiGaming/116/1020_116_FortuneGems2_CN.png"
                }
            ],
            "supportedCurrencies": [
                "CNY",
                "USD",
                "THB",
                "MMK",
                "INR",
                "IDO",
                "TMP",
                "MYR",
                "VNO",
                "NPR",
                "VND",
                "IDR",
                "JPY",
                "BND",
                "HKD",
                "PHP",
                "RUB",
                "BDT",
                "BRL",
                "MXN",
                "LAK",
                "KRW",
                "EUR",
                "KHR"
            ],
            "blockCountries": [],
            "isMaintain": false,
            "isEnabled": true,
            "isProvideCommission": false,
            "hasHedgeBet": false,
            "providerStatus": "Online",
            "isProviderOnline": true,
               "badge":drops_wins,
           
        },
         {
            "gameProviderId": 1085,
            "gameID": 6,
            "gameType": 2,
            "newGameType": 201,
            "rank": 1,
            "device": "d,m",
            "platform": "HTML5",
            "provider": "",
            "rtp": 0.960000,
            "rows": 3,
            "reels": 3,
            "lines": 5,
            "gameInfos": [
                {
                    "language": "en",
                    "gameName": "Golden Empire2",
                    "gameIconUrl": "https://cdn-test.cdn568.net/VAGaming/6/1085_6_GoldenEmpire2.png"
                },
                {
                    "language": "zh_cn",
                    "gameName": "黄金帝国2",
                    "gameIconUrl": "https://cdn-test.cdn568.net/VAGaming/6/1085_6_GoldenEmpire2_CN.png"
                }
            ],

            "blockCountries": [],
            "isMaintain": false,
            "isEnabled": true,
            "isProvideCommission": false,
            "hasHedgeBet": false,
            "providerStatus": "Online",
            "isProviderOnline": true,
               "badge":drops_wins,
            
        },
        {
            "gameProviderId": 35,
            "gameID": 134,
            "gameType": 2,
            "newGameType": 201,
            "rank": 3,
            "device": "d/m",
            "platform": "HTML5",
            "provider": "PGSoft",
            "rtp": 0.967500,
            "rows": 0,
            "reels": 0,
            "lines": 0,
            "gameInfos": [
                {
                    "language": "en",
                    "gameName": "Wild Bounty Showdown",
                    "gameIconUrl": "https://cdn-test.cdn568.net/images/games/PGSoft/WildBountyShowdown.jpg"
                },
                {
                    "language": "zh_cn",
                    "gameName": "赏金大对决",
                    "gameIconUrl": "https://cdn-test.cdn568.net/images/games/PGSoft/WildBountyShowdown_CN.jpg"
                }
            ],
            "supportedCurrencies": [
                "TMP",
                "BDT",
                "BRL",
                "CNY",
                "EUR",
                "IDR",
                "INR",
                "JPY",
                "KHR",
                "KRW",
                "LAK",
                "MMK",
                "MXN",
                "PHP",
                "THB",
                "USD",
                "VND"
            ],
            "blockCountries": [],
            "isMaintain": false,
            "isEnabled": true,
            "isProvideCommission": false,
            "hasHedgeBet": false,
            "providerStatus": "Online",
            "isProviderOnline": true,
            "badge":drops_wins,
            "badge_1":hot_rtp
        },
     {
            "gameProviderId": 3,
            "gameID": 397,
            "gameType": 2,
            "newGameType": 201,
            "rank": 8,
            "device": "d/m",
            "platform": "HTML5",
            "provider": "PragmaticPlay",
            "rtp": 0.980000,
            "rows": 4,
            "reels": 5,
            "lines": 1024,
            "gameInfos": [
                {
                    "language": "en",
                    "gameName": "Mahjong Wins",
                    "gameIconUrl": "https://cdn-test.cdn568.net/PragmaticPlay/397/3_397_MahjongWins.png?v=1"
                },
                {
                    "language": "zh_cn",
                    "gameName": "麻将大胜™",
                    "gameIconUrl": "https://cdn-test.cdn568.net/images/games/PragmaticPlay/3_397_MahjongWins_CN.png"
                }
            ],
            "supportedCurrencies": [
                "KZT",
                "IDO",
                "IDR",
                "TMP",
                "VND",
                "VNO",
                "AUD",
                "BDT",
                "BND",
                "BRL",
                "CAD",
                "CHF",
                "CNY",
                "EUR",
                "GBP",
                "HKD",
                "INR",
                "JPY",
                "KHR",
                "KRW",
                "LAK",
                "LKR",
                "MMK",
                "MXN",
                "MYR",
                "NGN",
                "NOK",
                "NPR",
                "NZD",
                "PHP",
                "PKR",
                "THB",
                "TRY",
                "USD",
                "ZAR"
            ],
            "blockCountries": [],
            "isMaintain": false,
            "isEnabled": true,
            "isProvideCommission": false,
            "hasHedgeBet": false,
            "providerStatus": "Online",
            "isProviderOnline": true,
             "badge":hot_rtp
        },
         {
            "gameProviderId": 1029,
            "gameID": 50,
            "gameType": 2,
            "newGameType": 201,
            "rank": 3,
            "device": "d,m",
            "platform": "HTML5",
            "provider": "568winGames",
            "rtp": 0.972800,
            "rows": 6,
            "reels": 5,
            "lines": -1,
            "gameInfos": [
                {
                    "language": "en",
                    "gameName": "Maneki Neko",
                    "gameIconUrl": "https://cdn-test.cdn568.net/568WinGames/50/manekiNeko.jpg"
                },
                {
                    "language": "ZH_CN",
                    "gameName": "招财猫",
                    "gameIconUrl": "https://cdn-test.cdn568.net/568WinGames/50/manekiNeko.jpg"
                }
            ],
            "supportedCurrencies": [
                "AED",
                "AUD",
                "BDT",
                "BRL",
                "CAD",
                "EUR",
                "GBP",
                "HKD",
                "IDO",
                "IDR",
                "INR",
                "JPY",
                "KHR",
                "KRW",
                "LAK",
                "MMK",
                "MYR",
                "NPR",
                "PHP",
                "SEK",
                "THB",
                "TMP",
                "USD",
                "VND",
                "VNO",
                "ZAR"
            ],
            "blockCountries": [
                "CN"
            ],
            "isMaintain": false,
            "isEnabled": true,
            "isProvideCommission": false,
            "hasHedgeBet": false,
            "providerStatus": "Online",
            "isProviderOnline": true,
            "badge":hot_rtp
        },
          
     {
            "gameProviderId": 1029,
            "gameID": 364,
            "gameType": 2,
            "newGameType": 201,
            "rank": 52,
            "device": "d/m",
            "platform": "HTML5",
            "provider": "568winGames",
            "rtp": 0.983830,
            "rows": 4,
            "reels": 5,
            "lines": 0,
            "gameInfos": [
                {
                    "language": "en",
                    "gameName": "300 Spartans",
                    "gameIconUrl": "https://cdn-test.cdn568.net/568winGames/364/300%20Spartans_200x200px.jpg"
                },
                 {
                    "language": "en",
                    "gameName": "300 Spartans",
                    "gameIconUrl": "https://cdn-test.cdn568.net/568winGames/364/300%20Spartans_200x200px.jpg"
                }
            ],
            "supportedCurrencies": [
                "UCC",
                "USD",
                "VND",
                "VNO",
                "ZAR",
                "AED",
                "AUD",
                "BDT",
                "BND",
                "BRL",
                "CAD",
                "CHF",
                "CLP",
                "CNY",
                "EUR",
                "GBP",
                "HKD",
                "IDO",
                "IDR",
                "INR",
                "JPY",
                "KHR",
                "KRW",
                "LAK",
                "LKR",
                "MMK",
                "MXN",
                "MYR",
                "NOK",
                "NPR",
                "NZD",
                "PEN",
                "PHP",
                "PKR",
                "RUB",
                "SEK",
                "THB",
                "TMP",
                "TRY"
            ],
            "blockCountries": [],
            "isMaintain": false,
            "isEnabled": true,
            "isProvideCommission": false,
            "hasHedgeBet": false,
            "providerStatus": "Online",
            "isProviderOnline": true,
               "badge":drops_wins,
               
           
        },
       
       
      
            
     {
            "gameProviderId": 1029,
            "gameID": 32,
            "gameType": 2,
            "newGameType": 201,
            "rank": 8,
            "device": "d,m",
            "platform": "HTML5",
            "provider": "568winGames",
            "rtp": 0.988800,
            "rows": 5,
            "reels": 3,
            "lines": 25,
            "gameInfos": [
                {
                    "language": "en",
                    "gameName": "Money Tree",
                    "gameIconUrl": "https://cdn-test.cdn568.net/568WinGames/32/moneyTree.jpg"
                },
                {
                    "language": "ZH_CN",
                    "gameName": "摇钱树",
                    "gameIconUrl": "https://cdn-test.cdn568.net/568WinGames/32/moneyTree.jpg"
                }
            ],
            "supportedCurrencies": [
                "AED",
                "AUD",
                "BDT",
                "BRL",
                "CAD",
                "EUR",
                "GBP",
                "HKD",
                "IDO",
                "IDR",
                "INR",
                "JPY",
                "KHR",
                "KRW",
                "LAK",
                "MMK",
                "MYR",
                "NPR",
                "PHP",
                "SEK",
                "THB",
                "TMP",
                "USD",
                "VND",
                "VNO",
                "ZAR"
            ],
            "blockCountries": [
                "CN"
            ],
            "isMaintain": false,
            "isEnabled": true,
            "isProvideCommission": false,
            "hasHedgeBet": false,
            "providerStatus": "Online",
            "isProviderOnline": true,
               "badge":drops_wins,
             "badge_1":hot_rtp
        },
           
       
];
export const newGames:Game[] = [
      {
            "gameProviderId": 3,
            "gameID": 529,
            "gameType": 2,
            "newGameType": 201,
            "rank": 16,
            "device": "d/m",
            "platform": "HTML5",
            "provider": "PragmaticPlay",
            "rtp": 0.960000,
            "rows": 6,
            "reels": 6,
            "lines": 0,
            "gameInfos": [
                {
                    "language": "en",
                    "gameName": "Wisdom of Athena 1000",
                    "gameIconUrl": "https://cdn-test.cdn568.net/PragmaticPlay/529/3_529_WisdomofAthena1000.png?v=5"
                },
                {
                    "language": "zh_cn",
                    "gameName": "雅典娜的智慧 1000",
                    "gameIconUrl": "https://cdn-test.cdn568.net/PragmaticPlay/529/3_529_WisdomOfAthena1000_CN.png"
                }
            ],
            "supportedCurrencies": [
                "KZT",
                "IDO",
                "IDR",
                "TMP",
                "VND",
                "VNO",
                "AUD",
                "BDT",
                "BND",
                "BRL",
                "CAD",
                "CHF",
                "CNY",
                "EUR",
                "GBP",
                "HKD",
                "INR",
                "JPY",
                "KHR",
                "KRW",
                "LAK",
                "LKR",
                "MMK",
                "MXN",
                "MYR",
                "NGN",
                "NOK",
                "NPR",
                "NZD",
                "PHP",
                "PKR",
                "THB",
                "TRY",
                "USD",
                "ZAR"
            ],
            "blockCountries": [],
            "isMaintain": false,
            "isEnabled": true,
            "isProvideCommission": false,
            "hasHedgeBet": false,
            "providerStatus": "Online",
            "isProviderOnline": true,
            "badge":new_svg
        },
         {
            "gameProviderId": 3,
            "gameID": 467,
            "gameType": 2,
            "newGameType": 201,
            "rank": 13,
            "device": "d/m",
            "platform": "HTML5",
            "provider": "PragmaticPlay",
            "rtp": 0.965000,
            "rows": 6,
            "reels": 5,
            "lines": 20,
            "gameInfos": [
                {
                    "language": "en",
                    "gameName": "Gates of Gatot Kaca 1000",
                    "gameIconUrl": "https://cdn-test.cdn568.net/PragmaticPlay/467/3_467_GatesofGatotKaca1000.png?v=6"
                },
                {
                    "language": "zh_cn",
                    "gameName": "印尼传奇迦多铎卡1000",
                    "gameIconUrl": "https://cdn-test.cdn568.net/images/games/PragmaticPlay/3_467_GatesofGatotKaca1000_CN.png"
                }
            ],
            "supportedCurrencies": [
                "KZT",
                "IDO",
                "IDR",
                "TMP",
                "VND",
                "VNO",
                "AUD",
                "BDT",
                "BND",
                "BRL",
                "CAD",
                "CHF",
                "CNY",
                "EUR",
                "GBP",
                "HKD",
                "INR",
                "JPY",
                "KHR",
                "KRW",
                "LAK",
                "LKR",
                "MMK",
                "MXN",
                "MYR",
                "NGN",
                "NOK",
                "NPR",
                "NZD",
                "PHP",
                "PKR",
                "THB",
                "TRY",
                "USD",
                "ZAR"
            ],
            "blockCountries": [],
            "isMaintain": false,
            "isEnabled": true,
            "isProvideCommission": false,
            "hasHedgeBet": false,
            "providerStatus": "Online",
            "isProviderOnline": true,
            "badge":new_svg
        },
         {
            "gameProviderId": 1085,
            "gameID": 2,
            "gameType": 2,
            "newGameType": 201,
            "rank": 3,
            "device": "d,m",
            "platform": "HTML5",
            "provider": "VAGaming",
            "rtp": 0.960000,
            "rows": 5,
            "reels": 4,
            "lines": -1,
            "gameInfos": [
                {
                    "language": "en",
                    "gameName": "Mahjong Self-Drawn Win 3",
                    "gameIconUrl": "https://cdn-test.cdn568.net/VAGaming/2/1085_2_MahjongSelfDrawnWin3.png"
                },
                {
                    "language": "zh_cn",
                    "gameName": "麻将自摸 3",
                    "gameIconUrl": "https://cdn-test.cdn568.net/VAGaming/2/1085_2_MahjongSelfDrawnWin3_CN.png"
                }
            ],
            "supportedCurrencies": [
                "TMP",
                "AOA",
                "AUD",
                "BDT",
                "BND",
                "BRL",
                "CAD",
                "CHF",
                "CNY",
                "ETB",
                "EUR",
                "GBP",
                "GHS",
                "HKD",
                "HUF",
                "IDO",
                "IDR",
                "INR",
                "IRR",
                "JPY",
                "KES",
                "KHR",
                "KRW",
                "KZT",
                "LAK",
                "LKR",
                "LSL",
                "MMK",
                "MWK",
                "MXN",
                "MYK",
                "MYR",
                "MZN",
                "NAD",
                "NGN",
                "NOK",
                "NPR",
                "NZD",
                "PEN",
                "PHP",
                "PLN",
                "RUB",
                "SEK",
                "SLL",
                "SZL",
                "THB",
                "TND",
                "TRY",
                "TZS",
                "UAH",
                "USD",
                "VND",
                "VNO",
                "XAF",
                "XOF",
                "ZAR",
                "ZMW"
            ],
            "blockCountries": [],
            "isMaintain": false,
            "isEnabled": true,
            "isProvideCommission": false,
            "hasHedgeBet": false,
            "providerStatus": "Online",
            "isProviderOnline": true,
            "badge":new_svg
        },
               {
            "gameProviderId": 1046,
            "gameID": 46,
            "gameType": 2,
            "newGameType": 201,
            "rank": 6,
            "device": "d,m",
            "platform": "HTML5",
            "provider": "FaChai",
            "rtp": 0.965000,
            "rows": -1,
            "reels": -1,
            "lines": 32400,
            "gameInfos": [
                {
                    "language": "en",
                    "gameName": "LEGEND OF INCA",
                    "gameIconUrl": "https://cdn-test.cdn568.net/Fachai/46/1046_46_LEGENDOFINCA.jpg"
                },
                {
                    "language": "ZH_CN",
                    "gameName": "印加传奇",
                    "gameIconUrl": "https://cdn-test.cdn568.net/Fachai/46/1046_46_LEGENDOFINCA_CN.jpg"
                }
            ],
            "supportedCurrencies": [
                "TMP",
                "AED",
                "AUD",
                "BDT",
                "BND",
                "BRL",
                "CAD",
                "CHF",
                "CLP",
                "CNY",
                "EUR",
                "GBP",
                "HKD",
                "IDR",
                "IDO",
                "INR",
                "JPY",
                "KRW",
                "LAK",
                "LKR",
                "MXN",
                "MYR",
                "NGN",
                "NOK",
                "NPR",
                "NZD",
                "PHP",
                "PKR",
                "RUB",
                "SEK",
                "SGD",
                "THB",
                "TRY",
                "USD",
                "VND",
                "VNO",
                "ZAR",
                "MMK"
            ],
            "blockCountries": [],
            "isMaintain": false,
            "isEnabled": true,
            "isProvideCommission": true,
            "hasHedgeBet": false,
            "providerStatus": "Online",
            "isProviderOnline": true,
            "badge":new_svg
        },
               {
            "gameProviderId": 1046,
            "gameID": 56,
            "gameType": 2,
            "newGameType": 201,
            "rank": 16,
            "device": "d/m",
            "platform": "HTML5",
            "provider": "FaChai",
            "rtp": 0.965000,
            "rows": 0,
            "reels": 0,
            "lines": 0,
            "gameInfos": [
                {
                    "language": "en",
                    "gameName": "TREASURES OF ODIN",
                    "gameIconUrl": "https://cdn-test.cdn568.net/FaChai/56/1046_56_TREASURESOFODIN.jpg"
                },
                {
                    "language": "zh_cn",
                    "gameName": "奥丁之宝",
                    "gameIconUrl": "https://cdn-test.cdn568.net/FaChai/56/1046_56_TREASURESOFODIN_CN.jpg"
                }
            ],
            "supportedCurrencies": [
                "TMP",
                "AED",
                "AUD",
                "BDT",
                "BND",
                "BRL",
                "CAD",
                "CHF",
                "CLP",
                "CNY",
                "EUR",
                "GBP",
                "HKD",
                "IDR",
                "IDO",
                "INR",
                "JPY",
                "KRW",
                "LAK",
                "LKR",
                "MXN",
                "MYR",
                "NGN",
                "NOK",
                "NPR",
                "NZD",
                "PHP",
                "PKR",
                "RUB",
                "SEK",
                "SGD",
                "THB",
                "TRY",
                "USD",
                "VND",
                "VNO",
                "ZAR",
                "MMK"
            ],
            "blockCountries": [],
            "isMaintain": false,
            "isEnabled": true,
            "isProvideCommission": false,
            "hasHedgeBet": false,
            "providerStatus": "Online",
            "isProviderOnline": true,
            "badge":new_svg
        },
]


export const topTableGames :Game[]= [
{
    "gameProviderId": 1020,
    "gameID": 145,
    "gameType": 3,
    "newGameType": 204,
    "rank": 153,
    "device": "d/m",
    "platform": "HTML5",
    "provider": "JiLiGaming",
    "rtp": 0,
    "rows": 0,
    "reels": 0,
    "lines": 0,
    "gameInfos": [
        {
            "language": "en",
            "gameName": "European Roulette",
            "gameIconUrl": "https://cdn-test.cdn568.net/JiLiGaming/145/1020_145_EuropeanRoulette.png"
        }
    ],
    "supportedCurrencies": [
        "CNY",
        "USD",
        "THB",
        "MMK",
        "INR",
        "IDO",
        "TMP",
        "MYR",
        "VNO",
        "NPR",
        "VND",
        "IDR",
        "JPY",
        "BND",
        "HKD",
        "PHP",
        "RUB",
        "BDT",
        "BRL",
        "MXN",
        "LAK",
        "KRW",
        "EUR",
        "KHR"
    ],
    "blockCountries": [],
    "isMaintain": false,
    "isEnabled": true,
    "isProvideCommission": false,
    "hasHedgeBet": false,
    "providerStatus": "Online",
    "isProviderOnline": true
},{
    "gameProviderId": 1029,
    "gameID": 338,
    "gameType": 3,
    "newGameType": 204,
    "rank": 183,
    "device": "d,m",
    "platform": "HTNL5",
    "provider": "568winGames",
    "rtp": 0,
    "rows": 0,
    "reels": 0,
    "lines": 0,
    "gameInfos": [
        {
            "language": "en",
            "gameName": "Royal Roulette",
            "gameIconUrl": "https://cdn-test.cdn568.net/568winGames/338/1029_338_royalroulette.png"
        },
        {
            "language": "ZH_CN",
            "gameName": "皇家轮盘",
            "gameIconUrl": "https://cdn-test.cdn568.net/568winGames/338/1029_338_royalroulette.png"
        }
    ],
    "supportedCurrencies": [
        "TMP",
        "AED",
        "AUD",
        "BDT",
        "CAD",
        "EUR",
        "GBP",
        "HKD",
        "IDR",
        "IDO",
        "INR",
        "JPY",
        "KRW",
        "MMK",
        "MYR",
        "NPR",
        "PHP",
        "SEK",
        "THB",
        "USD",
        "VND",
        "VNO",
        "ZAR",
        "NGN",
        "BND",
        "BRL",
        "CHF",
        "CNY",
        "LAK",
        "MXN",
        "NOK",
        "NZD",
        "RUB",
        "KHR"
    ],
    "blockCountries": [],
    "isMaintain": false,
    "isEnabled": true,
    "isProvideCommission": false,
    "hasHedgeBet": false,
    "providerStatus": "Online",
    "isProviderOnline": true
},
{
    "gameProviderId": 1020,
    "gameID": 72,
    "gameType": 3,
    "newGameType": 204,
    "rank": 89,
    "device": "d/m",
    "platform": "HTML5",
    "provider": "JiLiGaming",
    "rtp": 0,
    "rows": 0,
    "reels": 0,
    "lines": 0,
    "gameInfos": [
        {
            "language": "EN",
            "gameName": "Sic Bo",
            "gameIconUrl": "https://cdn-test.cdn568.net/JiLiGaming/72/310x190_EN_GAMEID_125.png"
        },
        {
            "language": "zh_cn",
            "gameName": "骰寶",
            "gameIconUrl": "https://cdn-test.cdn568.net/JiLiGaming/72/310x190_CN_GAMEID_125.png"
        }
    ],
    "supportedCurrencies": [
        "CNY",
        "USD",
        "THB",
        "MMK",
        "INR",
        "IDO",
        "TMP",
        "MYR",
        "VNO",
        "NPR",
        "VND",
        "IDR",
        "JPY",
        "BND",
        "HKD",
        "PHP",
        "RUB",
        "BDT",
        "BRL",
        "MXN",
        "LAK",
        "KRW",
        "EUR",
        "KHR"
    ],
    "blockCountries": [],
    "isMaintain": false,
    "isEnabled": true,
    "isProvideCommission": false,
    "hasHedgeBet": false,
    "providerStatus": "Online",
    "isProviderOnline": true
},
{
    "gameProviderId": 1020,
    "gameID": 67,
    "gameType": 3,
    "newGameType": 204,
    "rank": 148,
    "device": "d/m",
    "platform": "HTML5",
    "provider": "JiLiGaming",
    "rtp": 0,
    "rows": 0,
    "reels": 0,
    "lines": 0,
    "gameInfos": [
        {
            "language": "EN",
            "gameName": "Dragon & Tiger",
            "gameIconUrl": "https://cdn-test.cdn568.net/JiLiGaming/67/GameID_123_EN_310x190.png"
        },
        {
            "language": "zh_cn",
            "gameName": "龍虎鬥",
            "gameIconUrl": "https://cdn-test.cdn568.net/JiLiGaming/67/GameID_123_CN_310x190.png"
        }
    ],
    "supportedCurrencies": [
        "CNY",
        "USD",
        "THB",
        "MMK",
        "INR",
        "IDO",
        "TMP",
        "MYR",
        "VNO",
        "NPR",
        "VND",
        "IDR",
        "JPY",
        "BND",
        "HKD",
        "PHP",
        "RUB",
        "BDT",
        "BRL",
        "MXN",
        "LAK",
        "KRW",
        "EUR",
        "KHR"
    ],
    "blockCountries": [],
    "isMaintain": false,
    "isEnabled": true,
    "isProvideCommission": false,
    "hasHedgeBet": false,
    "providerStatus": "Online",
    "isProviderOnline": true
}
       
]